[Params]
_merge = "deep"

CharacterSet = "UTF-8"

Subtitle = ""

# PrivacyPolicyURL = ""

# HeaderImage = ""
# HeaderWidth = ""
# HeaderHeight = ""

mainSections = ["posts"]

[taxonomies]
# https://www.netlify.com/blog/2018/07/24/hugo-tips-how-to-create-author-pages/
_merge = "deep"
author = "author"
tag = "tag"
category = "category"
